### ISSUE TITLE
[Epic] Support different languages and cultures

### ISSUE THREAD

**Issue by bvizureanu** [code4romania/monitorizare-vot-android#26]
- [ ] Make sure all strings are being used from the @strings.xml file; 
- [ ] Remove hardcoded strings (where applicable).
- [ ] Make English the default value for the texts in the app;
- [ ] Follow up with a Romanian translation - provide an example for future translations.

**Comment by KrzysztofMadejski** [comment]
Some of the following strings I believe that don't apply to all contexts so should be moved to the API, dynamic definition in the database
Man/woman, rural/urban - that should depend on the country
```
 <!-- Branch selection -->
    <string name="branch_title">Choose the polling station</string>
    <string name="branch_subtitle">you are in</string>
    <string name="branch_county">County/District</string>
    <string name="branch_number">Polling station number</string>
    <string name="branch_change">Change the polling station</string>
    <string name="branch_question_environment">Choose the area of the station</string>
    <string name="branch_answer_rural">Rural</string>
    <string name="branch_answer_urban">Urban</string>
    <string name="branch_question_sex">The president of the polling station is:</string>
    <string name="branch_answer_man">Man</string>
    <string name="branch_answer_woman">Woman</string>
    <string name="branch_question_enter">Arrival time</string>
    <string name="branch_question_leave">Departure time</string>
    <string name="branch_choose_time_enter">Choose the time of your arrival</string>
    <string name="branch_choose_time_leave">Choose the time of your departure</string>
    <string name="invalid_branch_county">Choose the county/district</string>
    <string name="invalid_branch_number">Fill in the polling station number</string>
    <string name="invalid_branch_number_minus">The number of the station must be positive</string>
    <string name="invalid_branch_number_max">The maximum number for %1$s county is %2$s</string>
    <string name="invalid_branch_environment">Choose urban of rural</string>
    <string name="invalid_branch_sex">Choose man or woman</string>
    <string name="invalid_branch_time_in">Select the time of arrival</string>
```

Form names also should be dynamically defined in the database or am I wrong?
```
   <!-- Forms list -->
    <string name="form_1">Form A</string>
    <string name="form_1_letter">A</string>
    <string name="form_2">Form B</string>
    <string name="form_2_letter">B</string>
    <string name="form_3">Form C</string>
```

**Comment by KrzysztofMadejski** [comment]
See #38

**Comment by KrzysztofMadejski** [comment]
Multipart names to be translated

https://github.com/code4romania/monitorizare-vot-android/blob/translations/app/src/main/java/ro/code4/monitorizarevot/net/NetworkService.java#L44-L52

**Comment by KrzysztofMadejski** [comment]
Should we move [`County`](https://github.com/code4romania/monitorizare-vot-android/blob/translations/app/src/main/java/ro/code4/monitorizarevot/constants/County.java#L7-L50) to API or leave it here? I'd vote for moving it to API.
